package solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HOAPermit implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public HOAPermit() {
    }

}