package solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HOAPermit implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean approvalStatus;
   private java.lang.String meetingLocation;
   private java.lang.String meetingDate;

   public HOAPermit()
   {
   }

   public java.lang.Boolean getApprovalStatus()
   {
      return this.approvalStatus;
   }

   public void setApprovalStatus(java.lang.Boolean approvalStatus)
   {
      this.approvalStatus = approvalStatus;
   }

   public java.lang.String getMeetingLocation()
   {
      return this.meetingLocation;
   }

   public void setMeetingLocation(java.lang.String meetingLocation)
   {
      this.meetingLocation = meetingLocation;
   }

   public java.lang.String getMeetingDate()
   {
      return this.meetingDate;
   }

   public void setMeetingDate(java.lang.String meetingDate)
   {
      this.meetingDate = meetingDate;
   }

   public HOAPermit(java.lang.Boolean approvalStatus,
         java.lang.String meetingLocation, java.lang.String meetingDate)
   {
      this.approvalStatus = approvalStatus;
      this.meetingLocation = meetingLocation;
      this.meetingDate = meetingDate;
   }

}